// Code generated by mockery v2.52.2. DO NOT EDIT.

package mocks

import (
	context "context"

	domain "github.com/christhianjesus/crabi-challenge/internal/domain"
	mock "github.com/stretchr/testify/mock"
)

// PLDRepository is an autogenerated mock type for the PLDRepository type
type PLDRepository struct {
	mock.Mock
}

// IsValidUser provides a mock function with given fields: ctx, user
func (_m *PLDRepository) IsValidUser(ctx context.Context, user *domain.User) (bool, error) {
	ret := _m.Called(ctx, user)

	if len(ret) == 0 {
		panic("no return value specified for IsValidUser")
	}

	var r0 bool
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *domain.User) (bool, error)); ok {
		return rf(ctx, user)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *domain.User) bool); ok {
		r0 = rf(ctx, user)
	} else {
		r0 = ret.Get(0).(bool)
	}

	if rf, ok := ret.Get(1).(func(context.Context, *domain.User) error); ok {
		r1 = rf(ctx, user)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewPLDRepository creates a new instance of PLDRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewPLDRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *PLDRepository {
	mock := &PLDRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
